version: "3.2"

services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - "27017:27017"
  
  app:
    build: .
    command: npm start
    depends_on: 
      - db
    ports: 
      - "5000:5000"
    volumes:
      - .:/usr/app
    restart: always